/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poo_edfinalproject;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CadastroFreteScreen extends javax.swing.JFrame {

    ArrayList<Transportadora> listaFretes = new ArrayList();
    File arquivo = new File("cargasRecebidas.csv");

    public void refreshTela() {
        String aux = "";
        for (int i = 0; i < listaFretes.size(); i++) {
            aux += "Cidade Destino: " + listaFretes.get(i).getEnderecoClienteDestino() + " ";
            aux += listaFretes.get(i).getDistancaoCidadeDestino() + " km" + "\n";
            aux += "Destinatario: " + listaFretes.get(i).getNomeClienteDestino() + "\n";
            aux += "Remetente: " + listaFretes.get(i).getNomeRemetente() + "\n";
            aux += "Volume da Carga: " + listaFretes.get(i).getVolumeCarga() + " M³" + "\n";
            aux += "Valor do Frete: " + listaFretes.get(i).getVolumeCarga() * 
                    1.17 * listaFretes.get(i).getDistancaoCidadeDestino() + "\n\n";
        }
        txtAreaVerFretes.setText(aux);
        txtRemetente.setText("");
        txtDestinatario.setText("");
        txtVolCarga.setText("");
    }

    public void leituraArquivo() {
        FileReader fr = null;
        try {
            boolean existe = arquivo.exists();
            if (!existe) {
                try {
                    FileWriter fw = new FileWriter(arquivo, true);
                } catch (IOException ex) {
                    Logger.getLogger(CadastroFreteScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            listaFretes.clear();
            fr = new FileReader(arquivo);
            BufferedReader br = new BufferedReader(fr);
            while (br.ready()) {
                String[] t = br.readLine().split(",");
                Transportadora frete = new Transportadora();
                frete.setEnderecoClienteDestino(t[0]);
                frete.setDistancaoCidadeDestino(Float.parseFloat(t[1]));
                frete.setNomeClienteDestino(t[2]);
                frete.setNomeRemetente(t[3]);
                frete.setVolumeCarga(Float.parseFloat(t[4]));

                listaFretes.add(frete);
            }
            fr.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadastroFreteScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadastroFreteScreen.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(CadastroFreteScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        refreshTela();
    }

    public void escreverArquivo() throws IOException {
        boolean existe = arquivo.exists();
        if (existe) {
            arquivo.delete();
        }
        FileWriter fw = new FileWriter(arquivo, true);
        BufferedWriter bw = new BufferedWriter(fw);
        for (Transportadora frete : listaFretes) {
            bw.write(frete.getEnderecoClienteDestino() + ",");
            bw.write(frete.getDistancaoCidadeDestino() + ",");
            bw.write(frete.getNomeClienteDestino() + ",");
            bw.write(frete.getNomeRemetente() + ",");
            bw.write(frete.getVolumeCarga() + ",");
            bw.newLine();
        }
        bw.close();
        fw.close();
        

    }

    public CadastroFreteScreen() {
        initComponents();
        leituraArquivo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaVerFretes = new javax.swing.JTextArea();
        lblTxtBoxTitulo = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblRemetente = new javax.swing.JLabel();
        lblDestinatario = new javax.swing.JLabel();
        lblVolCarga = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRemetente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDestinatario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtVolCarga = new javax.swing.JTextField();
        citySelector = new javax.swing.JComboBox<>();
        bgCadastrarFreteButton = new javax.swing.JPanel();
        cadastrarFreteButton = new javax.swing.JLabel();
        bgVoltarAoMenuButton = new javax.swing.JPanel();
        voltarAoMenuButton = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 67, 86));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DS Solucoes Logisticas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 120));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        txtAreaVerFretes.setEditable(false);
        txtAreaVerFretes.setBackground(new java.awt.Color(204, 255, 255));
        txtAreaVerFretes.setColumns(20);
        txtAreaVerFretes.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtAreaVerFretes.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaVerFretes.setLineWrap(true);
        txtAreaVerFretes.setRows(5);
        txtAreaVerFretes.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtAreaVerFretes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 230, 350));

        lblTxtBoxTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTxtBoxTitulo.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lblTxtBoxTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTxtBoxTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTxtBoxTitulo.setText("Fretes cadastrados pendentes");
        jPanel1.add(lblTxtBoxTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 230, 30));

        lblDestino.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblDestino.setText("Cidade de destino");
        jPanel1.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        lblRemetente.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lblRemetente.setForeground(new java.awt.Color(0, 0, 0));
        lblRemetente.setText("Remetente");
        jPanel1.add(lblRemetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        lblDestinatario.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lblDestinatario.setForeground(new java.awt.Color(0, 0, 0));
        lblDestinatario.setText("Destinatario");
        jPanel1.add(lblDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        lblVolCarga.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lblVolCarga.setForeground(new java.awt.Color(0, 0, 0));
        lblVolCarga.setText("Volume da Carga");
        jPanel1.add(lblVolCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 300, 20));

        txtRemetente.setBackground(new java.awt.Color(255, 255, 255));
        txtRemetente.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtRemetente.setForeground(new java.awt.Color(51, 51, 51));
        txtRemetente.setBorder(null);
        jPanel1.add(txtRemetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 194, 300, 30));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 300, 20));

        txtDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        txtDestinatario.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtDestinatario.setForeground(new java.awt.Color(51, 51, 51));
        txtDestinatario.setBorder(null);
        jPanel1.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 300, 30));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 300, 20));

        txtVolCarga.setBackground(new java.awt.Color(255, 255, 255));
        txtVolCarga.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtVolCarga.setForeground(new java.awt.Color(51, 51, 51));
        txtVolCarga.setBorder(null);
        txtVolCarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVolCargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtVolCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 300, 30));

        citySelector.setBackground(new java.awt.Color(255, 255, 255));
        citySelector.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        citySelector.setForeground(new java.awt.Color(102, 102, 102));
        citySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bage", "Pelotas", "Rio Grande" }));
        citySelector.setBorder(null);
        citySelector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                citySelectorKeyPressed(evt);
            }
        });
        jPanel1.add(citySelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 300, -1));

        bgCadastrarFreteButton.setBackground(new java.awt.Color(0, 67, 86));

        cadastrarFreteButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        cadastrarFreteButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarFreteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarFreteButton.setText("Cadastrar Frete");
        cadastrarFreteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarFreteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarFreteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarFreteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarFreteButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgCadastrarFreteButtonLayout = new javax.swing.GroupLayout(bgCadastrarFreteButton);
        bgCadastrarFreteButton.setLayout(bgCadastrarFreteButtonLayout);
        bgCadastrarFreteButtonLayout.setHorizontalGroup(
            bgCadastrarFreteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCadastrarFreteButtonLayout.createSequentialGroup()
                .addComponent(cadastrarFreteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        bgCadastrarFreteButtonLayout.setVerticalGroup(
            bgCadastrarFreteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgCadastrarFreteButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cadastrarFreteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(bgCadastrarFreteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 170, 60));

        bgVoltarAoMenuButton.setBackground(new java.awt.Color(0, 67, 86));

        voltarAoMenuButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        voltarAoMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarAoMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarAoMenuButton.setText("Voltar ao menu");
        voltarAoMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarAoMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAoMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAoMenuButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgVoltarAoMenuButtonLayout = new javax.swing.GroupLayout(bgVoltarAoMenuButton);
        bgVoltarAoMenuButton.setLayout(bgVoltarAoMenuButtonLayout);
        bgVoltarAoMenuButtonLayout.setHorizontalGroup(
            bgVoltarAoMenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgVoltarAoMenuButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarAoMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgVoltarAoMenuButtonLayout.setVerticalGroup(
            bgVoltarAoMenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgVoltarAoMenuButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarAoMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(bgVoltarAoMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 170, 60));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 630, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFreteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFreteButtonMouseEntered
        bgCadastrarFreteButton.setBackground(new Color(127, 224, 251));
        cadastrarFreteButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_cadastrarFreteButtonMouseEntered

    private void cadastrarFreteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFreteButtonMouseExited
        bgCadastrarFreteButton.setBackground(new Color(0, 67, 86));
        cadastrarFreteButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_cadastrarFreteButtonMouseExited

    private void voltarAoMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAoMenuButtonMouseEntered
        bgVoltarAoMenuButton.setBackground(new Color(127, 224, 251));
        voltarAoMenuButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_voltarAoMenuButtonMouseEntered

    private void voltarAoMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAoMenuButtonMouseExited
        bgVoltarAoMenuButton.setBackground(new Color(0, 67, 86));
        voltarAoMenuButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_voltarAoMenuButtonMouseExited

    private void cadastrarFreteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFreteButtonMouseClicked
        try {
            Transportadora carga = new Transportadora();
            float distanca = switch (citySelector.getSelectedItem().toString()) {
                case "Bage" ->
                    distanca = 180;
                case "Pelotas" ->
                    distanca = 340;
                case "Rio Grande" ->
                    distanca = 400;
                default ->
                    throw new IllegalArgumentException("invalido");
            };
            carga.setEnderecoClienteDestino(citySelector.getSelectedItem().toString());
            carga.setDistancaoCidadeDestino(distanca);
            carga.setNomeClienteDestino(txtDestinatario.getText());
            carga.setNomeRemetente(txtRemetente.getText());
            carga.setVolumeCarga(Float.parseFloat(txtVolCarga.getText()));
            
            listaFretes.add(carga);
            escreverArquivo();
            refreshTela();
        } catch (IOException ex) {
            Logger.getLogger(CadastroFreteScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cadastrarFreteButtonMouseClicked

    private void citySelectorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citySelectorKeyPressed
        // JOptionPane.showMessageDialog(rootPane, "selected");
    }//GEN-LAST:event_citySelectorKeyPressed

    private void txtVolCargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVolCargaKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && (c == ',')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtVolCargaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFreteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFreteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFreteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFreteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFreteScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCadastrarFreteButton;
    private javax.swing.JPanel bgVoltarAoMenuButton;
    private javax.swing.JLabel cadastrarFreteButton;
    private javax.swing.JComboBox<String> citySelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblRemetente;
    private javax.swing.JLabel lblTxtBoxTitulo;
    private javax.swing.JLabel lblVolCarga;
    private javax.swing.JTextArea txtAreaVerFretes;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtRemetente;
    private javax.swing.JTextField txtVolCarga;
    private javax.swing.JLabel voltarAoMenuButton;
    // End of variables declaration//GEN-END:variables
}
