
package com.mycompany.poo_edfinalproject;
import java.awt.Color;

public class GestionarUsuarioScreen extends javax.swing.JFrame {


    public GestionarUsuarioScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        empName = new javax.swing.JLabel();
        lblNomeFunc = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNomeFunc = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtCPF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        lbTitle = new javax.swing.JLabel();
        lblApagarUser = new javax.swing.JLabel();
        lblSubTitleCadastro = new javax.swing.JLabel();
        bgCadastroButton = new javax.swing.JPanel();
        gerenciarUsuarioButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 67, 86));

        empName.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        empName.setForeground(new java.awt.Color(255, 255, 255));
        empName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empName.setText("DS Solucoes Logisticas");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(empName, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(empName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 120));

        lblNomeFunc.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        lblNomeFunc.setForeground(new java.awt.Color(51, 51, 51));
        lblNomeFunc.setText("Nome do Funcionario");
        jPanel1.add(lblNomeFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lblCPF.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(51, 51, 51));
        lblCPF.setText("CPF");
        jPanel1.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 270, 20));

        txtNomeFunc.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeFunc.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtNomeFunc.setForeground(new java.awt.Color(51, 51, 51));
        txtNomeFunc.setBorder(null);
        jPanel1.add(txtNomeFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 270, 30));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 270, 20));

        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(51, 51, 51));
        txtCPF.setBorder(null);
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, 30));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 270, 20));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setBorder(null);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 270, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 270, 20));

        lblPass.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        lblPass.setForeground(new java.awt.Color(51, 51, 51));
        lblPass.setText("Senha");
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 70, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 270, 20));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(153, 153, 153));
        txtPass.setToolTipText("");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, 30));

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Gestao dos usuarios");
        jPanel1.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 300, 40));

        lblApagarUser.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        lblApagarUser.setForeground(new java.awt.Color(51, 51, 51));
        lblApagarUser.setText("Apagar Usuario");
        jPanel1.add(lblApagarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 270, 40));

        lblSubTitleCadastro.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        lblSubTitleCadastro.setForeground(new java.awt.Color(51, 51, 51));
        lblSubTitleCadastro.setText("Cadastro");
        jPanel1.add(lblSubTitleCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, 40));

        bgCadastroButton.setBackground(new java.awt.Color(0, 67, 86));

        gerenciarUsuarioButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        gerenciarUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        gerenciarUsuarioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gerenciarUsuarioButton.setText("Cadastrar");
        gerenciarUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerenciarUsuarioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gerenciarUsuarioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gerenciarUsuarioButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgCadastroButtonLayout = new javax.swing.GroupLayout(bgCadastroButton);
        bgCadastroButton.setLayout(bgCadastroButtonLayout);
        bgCadastroButtonLayout.setHorizontalGroup(
            bgCadastroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerenciarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        bgCadastroButtonLayout.setVerticalGroup(
            bgCadastroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerenciarUsuarioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(bgCadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 140, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        txtPass.setText("");
    }//GEN-LAST:event_txtPassMouseClicked

    private void gerenciarUsuarioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciarUsuarioButtonMouseEntered
        bgCadastroButton.setBackground(new Color (127,224,251));
        gerenciarUsuarioButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_gerenciarUsuarioButtonMouseEntered

    private void gerenciarUsuarioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciarUsuarioButtonMouseExited
        bgCadastroButton.setBackground(new Color (0, 67, 86));
        gerenciarUsuarioButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_gerenciarUsuarioButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarUsuarioScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCadastroButton;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel gerenciarUsuarioButton;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lblApagarUser;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSubTitleCadastro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
